### ISSUE TITLE
Wrong match

### ISSUE THREAD

**Issue by ustroetz** [graphhopper/map-matching#13] opened 2015-02-18 12:14 UTC
What is the reason for this match? Is there a way for me as a user to improve the input?
Is it possible that the map matching algorithm respects bearing?

```
green line = matched track
points = input track
grey lines = OSM highways
```
![screen shot 2015-02-18 at 13 12 15](https://cloud.githubusercontent.com/assets/4493762/6247032/e862e224-b76f-11e4-810f-278481fe1197.png)
![screen shot 2015-02-18 at 13 12 05](https://cloud.githubusercontent.com/assets/4493762/6247034/eadda318-b76f-11e4-8242-389d6e255f43.png)

**Comment by karussell** [comment] 2015-02-18 12:19
If you change the separatedSearchDistance (to a higher value or something) is this fixed?

**Comment by ustroetz** [comment] 2015-02-18 12:53
No this did not fix it.

The GPX file I try to match is the below. I try to match it to the Istanbul Metro Extract.

```
<?xml version="1.0" encoding="UTF-8"?>
<gpx xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/0" version="1.0" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd" creator="gpx.py -- https://github.com/tkrajina/gpxpy">
<trk>
<name/>
<type/>
<desc/>
<trkseg>
<trkpt lat="41.0119089" lon="29.08910865">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0118916" lon="29.0892053">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0118725" lon="29.08929845">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01185135" lon="29.08939115">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0118263" lon="29.0894814">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0117989" lon="29.08956945">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0117678" lon="29.08965675">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0117371" lon="29.089747">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0117079" lon="29.08983775">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01167605" lon="29.08992865">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01164325" lon="29.09002255">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.011612" lon="29.0901183">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0115803" lon="29.0902159">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01154605" lon="29.09031725">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01151005" lon="29.09042">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01147355" lon="29.09052405">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01143775" lon="29.0906194">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0114005" lon="29.09071235">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0113635" lon="29.0908039">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01132835" lon="29.0908926">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0112937" lon="29.09098185">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0112593" lon="29.09107005">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0112247" lon="29.0911578">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0111918" lon="29.09124565">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0111619" lon="29.0913338">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.011134" lon="29.0914224">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0111091" lon="29.09151445">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.0110886" lon="29.09160745">
<time>2015-01-01T11:35:02Z</time></trkpt>
<trkpt lat="41.01107275" lon="29.09170405">
<time>2015-01-01T11:35:02Z</time></trkpt></trkseg></trk></gpx>
```

**Comment by karussell** [comment] 2015-02-18 12:54
Hmmh, I'll have a look in the next days

**Comment by ustroetz** [comment] 2015-02-18 12:55
Thanks!

**Comment by karussell** [comment] 2015-02-27 12:22
Hmmh, I cannot reproduce this with a car profile. Which profile did you use?

**Comment by ustroetz** [comment] 2015-02-27 19:58
Where can I set the profile? I guess I used the default profile.

**Comment by karussell** [comment] 2015-02-27 20:21
Hmmh, okay, the default was 'car'. (There is a new command line option 'vehicle=car', the old would have been too hidden via a config.properties)

**Comment by ustroetz** [comment] 2015-02-27 20:31
I'll give it a try again on Monday with the latest build and let you know my results.

Also we should add this parameter to the readme.

**Comment by karussell** [comment] 2015-02-27 20:34
Its already there ;)

**Comment by ustroetz** [comment] 2015-03-02 08:51
Hm, after cloning the latest build I get the following error:

```
$ ./map-matching.sh action=match gpx=test.gpx
Exception in thread "main" java.lang.NullPointerException
	at com.graphhopper.GraphHopper.getFirstVehicle(GraphHopper.java:128)
	at com.graphhopper.GraphHopper.init(GraphHopper.java:602)
	at com.graphhopper.matching.MapMatchingMain.start(MapMatchingMain.java:56)
	at com.graphhopper.matching.MapMatchingMain.main(MapMatchingMain.java:39)
```

**Comment by karussell** [comment] 2015-03-02 08:55
That is a GraphHopper issue. I'll fix.

**Comment by karussell** [comment] 2015-03-02 09:15
Would you update the graphhopper and map-matching repo?

**Comment by ustroetz** [comment] 2015-03-02 09:25
I have the latest map-matching repo. Though I am not using the graphhopper repo. It least I am not aware of it.

**Comment by karussell** [comment] 2015-03-02 09:27
Okay. Then you fetch graphhopper this via the snapshot repo. (which is currently rebuild only every 8 hours or so). You'll have to get it and install it or what 2 hours (will be build at 11 German time again I think)

**Comment by ustroetz** [comment] 2015-03-02 09:34
I'll wait and let you know what it does after lunch. Thanks for your help meanwhile!

**Comment by karussell** [comment] 2015-03-02 09:43
[From this snapshot repo](https://oss.sonatype.org/content/groups/public/com/graphhopper/graphhopper/0.4-SNAPSHOT/) it'll get the version (BTW: it is 12:00 not 11)

**Comment by ustroetz** [comment] 2015-03-02 12:37
Still get the same error. Probable because I have the wron GrapHopper version. It says:
```
2015-03-02 13:32:43,830 [main] INFO  com.graphhopper.GraphHopper - version 0.4|2015-02-27T17:00:27+0000 (4,11,3,2,2)
```
Where can I set which GrapHopper it  should use/fetch?

**Comment by karussell** [comment] 2015-03-02 12:39
you clone the main repo and just install it locally: `mvn clean install -DskipTests=true`

**Comment by ustroetz** [comment] 2015-03-02 12:58
Okay, got it to work. However still matches like before. I used the car profile.

**Comment by karussell** [comment] 2015-03-03 15:19
Can you create an integration or even better unit test for it? Maybe we use different PBF files

**Comment by ustroetz** [comment] 2015-03-03 15:25
I am using this PBF file: https://s3.amazonaws.com/metro-extracts.mapzen.com/istanbul_turkey.osm.pbf

I will look into integration or unit test tomorrow morning.

**Comment by ustroetz** [comment] 2015-03-04 08:48
I can't find anything in the documentation about integration or unit tests. Maybe you can reference me to documents on how to do that. Else we can also leave this issue for now.

**Comment by karussell** [comment] 2015-03-04 09:43
No problem, an example of a unit test you can find [in the source](https://github.com/graphhopper/map-matching/blob/master/src/test/java/com/graphhopper/matching/MapMatchingTest.java#L60). I tried it with the pbf file you mentioned and can now reproduce it. Will investigate.

**Comment by karussell** [comment] 2015-03-04 10:19
The reason is that the highway (Yunus Emre) is slightly better for the path finding algorithm (e.g. 60kph vs. 30kph). Still here the shorter street should be significantly preferred as there are many GPX points which are also close. This will be fixed.

**Comment by karussell** [comment] 2015-03-04 10:20
(There was a mechanism to prefer edges with many GPX points before but due to other problems I removed it at that time. Will investigate it next week.)

**Comment by ustroetz** [comment] 2015-03-04 10:20
:thumbsup: Sounds great!

**Comment by karussell** [comment] 2016-10-12 12:52
Merged branch with a fix https://github.com/graphhopper/map-matching/compare/issue_13

**Closed by karussell** 2016-10-12 12:52 UTC
Labels: bug
